### ISSUE TITLE
RFC: Long compilation time

### ISSUE THREAD

**Issue by bajr** [Rust-Proof/rustproof#103]
The LALRPOP documentation indicates that it can be run manually to generate a new parser, rather than automatically compiling each time cargo build is run. I'd like to hear what you all think about changing current process to compile the parser manually in order to save time when working on non-parsing things.

**Comment by salterm** [comment]
Lalrpop will only run if there are .lalrpop files to work on; once the grammars are fixed, the .lalrpop files can be moved elsewhere and we can just use the previously-generated functions. It shouldn't even be re-compiling if the .lalrpop files have not changed between builds, assuming you don't clean every time.

**Comment by VSchuster** [comment]
Close this?
