### ISSUE TITLE
Attribute type declaration should use rust reserved names

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#118]
ie change b to bool.
think about int vs i32, i8, ...

**Comment by salterm** [comment]
I'm fine with expanding b -> bool, and i -> int is okay (although "int" isn't a rust type anymore, but i -> i64, i32, u8, ... is more problematic. That implies that we're actually going to be remembering the size of our number types.

**Comment by arc3x** [comment]
I agree. I think int is fine
