### ISSUE TITLE
Possible bug in vc processing relating to if branches

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#178]
For this function rustproof returns 'valid', but it shouldnt.

```
#[condition(pre="x: int < 2147483642 && x: int > -2147483648", post="return: int == x: int +5")]
fn add_five(x: i32) -> i32 {
    if false {
        x+2
    } else {
        x+2
    }
}
```

When I put the verification condition generated by rustproof for the above function into the online z3 it says 'sat' implying an invalid VC.

note: my testing makes me think its an issue with libsmt

note: below rustproof returns invalid like it should and online z3 agrees.
```
#[condition(pre="x: int < 2147483642 && x: int > -2147483648", post="return: int == x: int +5")]
fn add_five(x: i32) -> i32 {
    x+2
}
```

note: below rustproof returns valid like it should and online z3 agrees.
```
#[condition(pre="x: int < 2147483642 && x: int > -2147483648", post="return: int == x: int +5")]
fn add_five(x: i32) -> i32 {
    x+5
}
```

**Comment by salterm** [comment]
Is this issue caused by #182 ?

**Comment by arc3x** [comment]
Confirmed. Closing as duplicate of #182
