### ISSUE TITLE
something broke for tuple replacements

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#192]
when executing an example using a checked add the tuple replacement doesn't happen anymore. This is probably due to sami's new change.

```
bb1
processing statement	return = (tmp1.0: i32)
into expression		((return : i32) == ((x : i32) + (5)))
new expression		((return : i32) == ((x : i32) + (5)))
```

**Comment by ssahli** [comment]
This was happening to me prior to the tuple changes.

I did a fresh clone from the repo last night (PR #183) and replacements weren't happening.

Please make sure that this issue occurs only on tuple assignments.

**Comment by ssahli** [comment]
Resolved; the issue wasn't with tuples but with return types. See issue #196 for follow-up
