### ISSUE TITLE
Something broke for overflow checking

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#213]
```
#[condition(pre="(x: i32 < 2147483647:i32) && (x: i32 > -2147483653:i32)", post="return: i32 == (x: i32 +5:i32)")]
fn add_five(x: i32) -> i32 {
    x+5
}
```
Should be invalid, but it returns valid. This bug was introduced on August 6th 2016.

**Comment by arc3x** [comment]
This is happening because of our switch to signed ops in our libsmt output. 
I dont understand why this is happening. We should discuss it.

This code in smt_output/mod.rs is causing the failure
```
&Expression::VariableMapping (ref v) => {
                match v.var_type.as_ref() {
                    "bool" => { return self.new_var(Some(&v.name), core::Sorts::Bool); },
                    "i8" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(8)); },
                    "i16" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(16)); },
                    "i32" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(32)); },
                    "i64" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "u8" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(8)); },
                    "u16" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(16)); },
                    "u32" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(32)); },
                    "u64" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    _ => { rp_error!("Invalid or Unsupported type for variable: \"{}\" : \"{}\"", v.name, v.var_type); },
                }
            },
            &Expression::BooleanLiteral (ref b) => {
                return self.new_const(core::OpCodes::Const(*b));
            },
            &Expression::UnsignedBitVector (ref u) => {
                return bv_const!(self, u.value, u.size as usize);
            },
            &Expression::SignedBitVector (ref s) => {
                return bv_const!(self, s.value as u64, s.size as usize);
            }
```

The issue can be solved by using entirely 64 length bit vectors
```
&Expression::VariableMapping (ref v) => {
                match v.var_type.as_ref() {
                    "bool" => { return self.new_var(Some(&v.name), core::Sorts::Bool); },
                    "i8" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "i16" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "i32" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "i64" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "u8" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "u16" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "u32" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    "u64" => { return self.new_var(Some(&v.name), bitvec::Sorts::BitVector(64)); },
                    _ => { rp_error!("Invalid or Unsupported type for variable: \"{}\" : \"{}\"", v.name, v.var_type); },
                }
            },
            &Expression::BooleanLiteral (ref b) => {
                return self.new_const(core::OpCodes::Const(*b));
            },
            &Expression::UnsignedBitVector (ref u) => {
                return bv_const!(self, u.value, 64 as usize);
            },
            &Expression::SignedBitVector (ref s) => {
                return bv_const!(self, s.value as u64, 64 as usize);
            }
```

**Comment by bajr** [comment]
The SMT-LIB language standard makes no effort to stop or warn about bit vector overflow when we apply variables or literals to it.

So, for example, something like `(_ bv18446744073709551615 64)` (u64::MAX) becomes `0xffffffffffffffff`, but `(_ bv18446744073709551616 64)` becomes `0x0000000000000000`.

The latter actually gets read correctly by z3, but it loses the 65th bit with it's assigned to the 64 size bit vector.

I think a 'solution' might be to make all bit vectors given to z3 64-bits, which would make the problem of integer overflow ​*inside*​ z3 easier to handle (just make sure they fit within the user-defined size, i.e. for i32 make sure all literals are <=2^31 before making them 64-bit vectors in z3)

But there would still be weird edge cases, like what happens with `(bvadd (_bv1 64) (_ bv<u64::MAX> 64))` and how can we reasonably handle them. Another edge case would be something like `(bvadd x (_ bv5 64))`, z3 will attempt to find a value for x that might be near u64::MAX and cause bvadd to return an overflowed number.

**Comment by salterm** [comment]
So it can't compute something like x + 5 < u64::MAX, because x+5 will be stored in a 64-length bitvector and that value will overflow during the calculation, and end up as a value less than the maximum. Is that the gist of it?

Something like... it can't detect overflow because it overflows doing the check itself?

**Comment by bajr** [comment]
@salterm Correct.

**Comment by salterm** [comment]
Signed and unsigned addition and subtraction have been reimplemented in a way that avoids these issues. Division, modulus ( #232 ), and multiplication ( #233 ) are still outstanding.
