### ISSUE TITLE
Change attribute MAX to max_value (and MIN)

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#241]
rust uses max_value, so why not bring rustproof inline with that?

**Comment by salterm** [comment]
Will question the sponsors as to their preference.

**Comment by bajr** [comment]
If relevant, turns out rust also uses MAX: https://doc.rust-lang.org/std/i32/

**Comment by salterm** [comment]
So it does; looks like the constant itself is set by calling max/min_value(). However it adds credence to us leaving it as-is.

**Comment by salterm** [comment]
Sponsors ruled this a non-issue. No change will be made.
