### ISSUE TITLE
Unimplemented terminator type blocks assertions with i32::max_value()

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#242]
The following code
```
#[condition(pre="(x: i32 <= i32::MAX - 5:i32) && (x: i32 >= i32::MIN + 5:i32)", post="return: i32 == (x: i32 +5:i32)")]
fn add_five_i32_valid(x: i32) -> i32 {
    assert!(x <= i32::max_value());
    assert!(x >= (i32::min_value()-5));
    x+5
}
```

Does not compile due to i32::max_value(). It would be nice if this worked.

**Comment by salterm** [comment]
That's a function call, so we'd have to implement functions for that to work, I would think.

**Comment by arc3x** [comment]
ya, or we could hack it to resolve to a value. Or users can just supply hard coded values when wanted
