### ISSUE TITLE
Travis CI hangs during cargo test

### ISSUE THREAD

**Issue by ssahli** [Rust-Proof/rustproof#271]
Specifically, hangs when running test_example_file() in src/tests/system_tests.rs. We suspect it may be an issue with buffered read in libsmt

EDIT:

The issue is with recent bugs in cargo. The issue is specifically when an instance of cargo is called within another instance of cargo using `std::process::Command`.

The last working nightly build:
```
rustc 1.12.0-nightly (8787a1233 2016-08-11)
binary: rustc
commit-hash: 8787a12334439d47e931be26fef53381ce337c3a
commit-date: 2016-08-11
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

**Comment by salterm** [comment]
Seems to be related to a recent change in Cargo. Currently we are using the Rust nightly build for 2016-08-11 until the issue is ameliorated.

**Comment by ssahli** [comment]
Issue still exists with the following rust version:
```
rustc 1.13.0-nightly (aef6971ca 2016-08-17)
binary: rustc
commit-hash: aef6971ca96be5f04291420cc773b8bfacb8b36d
commit-date: 2016-08-17
host: x86_64-apple-darwin
release: 1.13.0-nightly
```

**Comment by VSchuster** [comment]
Decided to use 1.12.0-nightly specifically.  New issue created for re-implementing tests.
