### ISSUE TITLE
libsmt isn't properly catching errors

### ISSUE THREAD

**Issue by salterm** [Rust-Proof/rustproof#280]
Running this example:
```
// Valid
#[condition(pre="x: bool == false", post="return: bool == true")]
fn foo(x: bool) -> bool {
		x ^ true
}
```
...hits an unimplemented!() match branch in smt_output, where we have an Ok object returned from libsmt that is neither Sat nor Unsat.

I believe the issue is that error messages still have "unsat" or "sat" at the end of output.

**Comment by arc3x** [comment]
Note: due to recently merged code this doesn't cause errors anymore. Errors are caught and reported now as of PR #282
