### ISSUE TITLE
Can't publish to crates.io with github-based dependencies

### ISSUE THREAD

**Issue by salterm** [Rust-Proof/rustproof#312]
We'll have to either:
*make our fork of libsmt a crate
*include the portions of libsmt we use into rustproof
*get sushant94 to update their repo and package it as a crate
*find a way to not use libsmt

**Comment by salterm** [comment]
My vote is to cannibalize libsmt. This may also fix our system testing issue.

**Comment by selenesal** [comment]
Issue bypassed by making our version of libsmt into a crate as well.
